const reduxString = {
    BACKUP_LIST_CONTACT: 'BACKUP_LIST_CONTACT',
    SET_LIST_CONTACT: 'SET_LIST_CONTACT',
    SET_RECENT_CONTACT: 'SET_RECENT_CONTACT',
    SET_DETAIL_DATA: 'SET_DETAIL_DATA',
    SET_ERROR: 'SET_ERROR',
    SET_MESSAGE: 'SET_MESSAGE',
    REQUEST_DATA: 'REQUEST_DATA',
    REQUEST_DETAIL_DATA: 'REQUEST_DETAIL_DATA',
    REQUEST_SUBMIT: 'REQUEST_SUBMIT',
    REFRESH_DATA: 'REFRESH_DATA',
}

export default reduxString